
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto_0103;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Coment_m = 24;
  public static final int Numero = 12;
  public static final int Mas = 19;
  public static final int ERROR = 27;
  public static final int Comilla_simple = 21;
  public static final int Llave_c = 4;
  public static final int G_ondulado = 14;
  public static final int Llave_a = 3;
  public static final int Coma = 15;
  public static final int Separador = 7;
  public static final int Or = 17;
  public static final int P_coma = 5;
  public static final int Asterisco = 18;
  public static final int Cadena = 9;
  public static final int Conj = 2;
  public static final int EOF = 0;
  public static final int Comilla_doble = 22;
  public static final int Interrogacion = 20;
  public static final int D_puntos = 6;
  public static final int error = 1;
  public static final int Flecha = 8;
  public static final int Id = 10;
  public static final int Punto = 16;
  public static final int Espacio = 25;
  public static final int Letra = 11;
  public static final int C_signo = 13;
  public static final int Coment_s = 23;
  public static final int Cadena_Ll = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Conj",
  "Llave_a",
  "Llave_c",
  "P_coma",
  "D_puntos",
  "Separador",
  "Flecha",
  "Cadena",
  "Id",
  "Letra",
  "Numero",
  "C_signo",
  "G_ondulado",
  "Coma",
  "Punto",
  "Or",
  "Asterisco",
  "Mas",
  "Interrogacion",
  "Comilla_simple",
  "Comilla_doble",
  "Coment_s",
  "Coment_m",
  "Espacio",
  "Cadena_Ll",
  "ERROR"
  };
}

