
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto_0103.ExpressionTree;

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int Punto = 3;
  public static final int Cadena = 2;
  public static final int ERROR = 9;
  public static final int EOF = 0;
  public static final int Cadena_Ll = 8;
  public static final int Or = 4;
  public static final int error = 1;
  public static final int Asterisco = 5;
  public static final int Interrogacion = 6;
  public static final int Mas = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Cadena",
  "Punto",
  "Or",
  "Asterisco",
  "Interrogacion",
  "Mas",
  "Cadena_Ll",
  "ERROR"
  };
}

